language: php

php:
    - 7.0
    - 7.1
    - 7.2

services:
  - postgresql
  - mysql

matrix:
  fast_finish: true

before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    - psql -c 'create database test;' -U postgres
    - travis_retry composer install --prefer-source --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
